# Generated by Django 5.0.2 on 2024-05-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Filmoholic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='username',
        ),
    ]
