# Generated by Django 5.0.2 on 2024-05-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmoholic_app', '0002_rename_full_name_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='static/')),
                ('release_date', models.DateField()),
                ('imdb_rating', models.CharField(max_length=100)),
                ('movie_director', models.CharField(max_length=200)),
                ('movie_cast', models.CharField(max_length=1000)),
                ('movie_language', models.CharField(max_length=100)),
                ('movie_genre', models.CharField(max_length=100)),
            ],
        ),
    ]
