# Generated by Django 5.0.2 on 2024-06-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmoholic_app', '0003_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='filmbuzz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_image', models.ImageField(upload_to='static/')),
                ('fb_title', models.CharField(max_length=500)),
                ('fb_description', models.TextField(max_length=1000)),
            ],
        ),
    ]
