# Generated by Django 5.0.2 on 2024-08-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmoholic_app', '0004_filmbuzz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_image', models.ImageField(upload_to='static/')),
                ('m_name', models.CharField(max_length=500)),
                ('t_link', models.TextField(max_length=1000)),
                ('m_cast', models.CharField(max_length=1000)),
            ],
        ),
    ]
